// src/pages/pricing.jsx
import React, { useEffect, useRef, useState } from "react";
import { Lock, RotateCcw } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import SiteHeader from "../components/SiteHeader.jsx";
import SiteFooter from "../components/SiteFooter.jsx";
import Button from "@/components/ui/Button";

const Pricing = () => {
  const navigate = useNavigate();
  const [isVisible, setIsVisible] = useState(false);

  // Stripe direct checkout (optional secondary path)
  const [unlocking, setUnlocking] = useState(false);
  const [unlockErr, setUnlockErr] = useState("");
  const checkoutInFlight = useRef(false);

  useEffect(() => {
    const timer = setTimeout(() => setIsVisible(true), 120);
    return () => clearTimeout(timer);
  }, []);

  // Reset state on back navigation from Stripe (bfcache restore)
  useEffect(() => {
    const reset = () => {
      checkoutInFlight.current = false;
      setUnlocking(false);
      setUnlockErr("");
    };
    const onPageShow = () => reset();
    const onVisibility = () => {
      if (!document.hidden) reset();
    };

    window.addEventListener("pageshow", onPageShow);
    document.addEventListener("visibilitychange", onVisibility);
    return () => {
      window.removeEventListener("pageshow", onPageShow);
      document.removeEventListener("visibilitychange", onVisibility);
    };
  }, []);

  // ✅ Primary funnel step: go to Wizard Intro screen
  const goActivateIntro = () => {
    try {
      localStorage.setItem("entryPoint", "pricing");
    } catch {}
    navigate("/activate", { state: { from: "pricing" } });
  };

  // Optional: direct Stripe checkout (for very warm users)
  async function beginCheckout() {
    if (checkoutInFlight.current) return;
    checkoutInFlight.current = true;

    setUnlocking(true);
    setUnlockErr("");

    try {
      const res = await fetch("/.netlify/functions/create-checkout-session", {
        method: "POST",
        headers: { "Content-Type": "application/json", Accept: "application/json" },
        body: JSON.stringify({ stackKey: "growth" }), // single price; metadata still useful
      });

      const payload = await res.json().catch(() => ({}));
      if (!res.ok || !payload?.url) {
        const msg = payload?.error || `Checkout failed (${res.status}). Please try again.`;
        throw new Error(msg);
      }

      window.location.href = payload.url;
    } catch (e) {
      console.error(e);
      setUnlockErr(e?.message || "Couldn’t start checkout. Please try again.");
      setUnlocking(false);
      checkoutInFlight.current = false;
    }
  }

  return (
    <div className="bg-neutral-950 font-sans text-white flex flex-col min-h-screen">
      <SiteHeader />

      <main
        className={`flex-grow w-full max-w-6xl mx-auto px-4 sm:px-6 pt-10 pb-10 transition-all duration-700 ${
          isVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-4"
        }`}
      >
        {/* Top block */}
        <div className="text-center space-y-4">
          <div className="inline-flex items-center gap-2 rounded-full border border-lime-400/25 bg-lime-500/10 px-3 py-1 text-xs text-lime-300">
            One-time activation • No subscription
          </div>

         <h1 className="text-3xl md:text-5xl font-extrabold tracking-tight">
  Unlock Your AI-Personalized <span className="text-lime-400">Credit Route</span>
</h1>
<p className="mt-4 text-lg text-zinc-300">
  One-time activation — <span className="text-white font-semibold">$29</span>
</p>

          <p className="mx-auto max-w-2xl text-lg text-neutral-300">
  You’re not buying a list of apps. You’re unlocking a <span className="text-white font-semibold">personalized credit strategy</span> that combines the right tools so they work together.
</p>

          <p className="text-sm text-neutral-400">
            No credit pull • No sensitive financial data required • Instant access after checkout
          </p>
        </div>

        {/* Pricing layout */}
        <div className="mt-10 grid gap-8 lg:grid-cols-12 lg:items-start">
          {/* Left: Activation includes */}
<div className="lg:col-span-7 space-y-6">
  <div className="rounded-2xl border border-white/10 bg-white/[0.04] p-6">
    <h3 className="text-base font-semibold text-white">Your Credit Route Includes</h3>

    <div className="mt-4 grid gap-4 sm:grid-cols-2 text-sm text-neutral-300">
      <ul className="space-y-2 list-disc pl-5">
        <li>Personalized Credit Route generated by AI</li>
        <li>Direct links to the tools in your route</li>
        <li>Smart reroutes if a tool isn’t available</li>
      </ul>
      <ul className="space-y-2 list-disc pl-5">
        <li>Step-by-step activation guide</li>
        <li>Printable execution blueprint</li>
        <li>Built for real-life habits</li>
      </ul>
    </div>

    <div className="mt-4 text-xs text-neutral-500">
      Results vary by credit profile and reporting timelines.
    </div>
  </div>

  <div className="flex flex-col sm:flex-row gap-3">
    <Link to="/sixsimple" className="inline-flex">
      <Button variant="secondary" size="md">See How It Works</Button>
    </Link>
    <Link to="/preview" className="inline-flex">
      <Button variant="secondary" size="md">See My Credit Routes</Button>
    </Link>
  </div>
</div>

          {/* Right: Price card */}
          <div className="lg:col-span-5">
            <div className="rounded-2xl border border-white/10 bg-white/[0.04] p-6 shadow-xl shadow-lime-500/10">
              <div className="flex items-start justify-between gap-4">
                <div>
                  <div className="text-sm text-neutral-300">Credit Route Activation</div>
<div className="mt-1 text-4xl font-extrabold">$29</div>
<div className="mt-1 text-sm text-neutral-400">One-time payment</div>
<div className="mt-2 text-xs text-neutral-500">
  Less than the cost of signing up for the wrong credit app.
</div>

                <div className="rounded-full border border-lime-400/25 bg-lime-500/10 px-3 py-1 text-xs font-medium text-lime-300">
                  Recommended
                </div>
              </div>

              <div className="mt-5 space-y-2 text-sm text-neutral-300">
                <div className="flex items-center gap-2"><span className="text-lime-300">✓</span> Full route + reroutes</div>
                <div className="flex items-center gap-2"><span className="text-lime-300">✓</span> Step-by-step activation</div>
                <div className="flex items-center gap-2"><span className="text-lime-300">✓</span> Printable blueprint</div>
              </div>

              {/* Primary = Wizard Intro */}
              <div className="mt-6 space-y-3">
                <Button
                  size="lg"
                  className="w-full bg-gradient-to-r from-lime-500 to-emerald-500 shadow-xl shadow-lime-500/40 transition-all duration-200 hover:scale-[1.02]"
                  onClick={goActivateIntro}
                >
                  🚀 🚀 Activate My Personalized Credit Route
                </Button>

                {/* Optional direct purchase path */}
                <Button
                  size="md"
                  variant="secondary"
                  className="w-full"
                  onClick={beginCheckout}
                  disabled={unlocking}
                >
                  {unlocking ? "Opening Stripe…" : "Activate Now — $29"}
                </Button>

                {unlockErr && <div className="text-sm text-red-300">{unlockErr}</div>}

                <p className="text-xs text-neutral-400">
                  Secure checkout • Instant access • No credit check required
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Refresh (future) — de-emphasized */}
        <section
          className={`mt-14 border-t border-neutral-800 pt-8 text-center space-y-4 max-w-3xl mx-auto transition-all duration-700 ${
            isVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-4"
          }`}
          style={{ transitionDelay: "240ms" }}
        >
          <h2 className="text-xl md:text-2xl font-semibold text-white flex items-center justify-center gap-2 tracking-tight">
            <RotateCcw className="w-5 h-5 stroke-lime-400" strokeWidth="1.5" />
            Refresh Later (Optional)
          </h2>

          <p className="text-neutral-400 text-sm">
  Life changes — and your Credit Route can evolve with it. You’ll be able to refresh your route later as new reporting tools become available.
</p>

          <div className="pt-2">
            <Button variant="secondary" size="md" disabled>
              <Lock className="w-4 h-4 mr-2" />
              Refresh Available Later
            </Button>
          </div>
        </section>
      </main>

      <SiteFooter />
    </div>
  );
};

export default Pricing;